//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllResult
    {
        public int RunnerId { get; set; }
        public string NameRunner { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public byte MarathonId { get; set; }
        public string MarathonName { get; set; }
        public string EventTypeId { get; set; }
        public string EventTypeName { get; set; }
        public Nullable<int> RaceTime { get; set; }
        public string CountryName { get; set; }
    }
}
