//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants2022
    {
        public int RegistrationEventId { get; set; }
        public int RegistrationId { get; set; }
        public string EventId { get; set; }
        public int BibNumber { get; set; }
        public Nullable<int> RaceTime { get; set; }
        public int Expr1 { get; set; }
        public int RunnerId { get; set; }
        public System.DateTime RegistrationDateTime { get; set; }
        public string RaceKitOptionId { get; set; }
        public byte RegistrationStatusId { get; set; }
        public decimal Cost { get; set; }
        public int CharityId { get; set; }
        public decimal SponsorshipTarget { get; set; }
        public int Expr2 { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CountryCode { get; set; }
        public string Expr3 { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RoleId { get; set; }
        public string Patch { get; set; }
        public string Expr4 { get; set; }
        public string CountryName { get; set; }
        public string CountryFlag { get; set; }
        public byte Expr5 { get; set; }
        public string RegistrationStatus { get; set; }
        public string Expr6 { get; set; }
        public string EventName { get; set; }
        public string EventTypeId { get; set; }
        public byte MarathonId { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<decimal> Expr7 { get; set; }
        public Nullable<short> MaxParticipants { get; set; }
        public byte Expr8 { get; set; }
        public string MarathonName { get; set; }
        public string CityName { get; set; }
        public string Expr9 { get; set; }
        public Nullable<short> YearHeld { get; set; }
    }
}
