//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positions
    {
        public short Positionid { get; set; }
        public string Position_Name { get; set; }
        public string Position_Description { get; set; }
        public string Pay_Period { get; set; }
        public decimal Pay_Rate { get; set; }
    }
}
