//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunnerResult
    {
        public int RunnerId { get; set; }
        public string MarathonName { get; set; }
        public string EventTypeName { get; set; }
        public Nullable<int> RaceTime { get; set; }
        public Nullable<long> place { get; set; }
    }
}
