//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Runner
    {
        public int RunnerId { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual Country Country3 { get; set; }
        public virtual Country Country4 { get; set; }
        public virtual Country Country5 { get; set; }
        public virtual Country Country6 { get; set; }
        public virtual Country Country7 { get; set; }
        public virtual Country Country8 { get; set; }
        public virtual Country Country9 { get; set; }
        public virtual Country Country10 { get; set; }
        public virtual Country Country11 { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Gender Gender2 { get; set; }
        public virtual Gender Gender3 { get; set; }
        public virtual Gender Gender4 { get; set; }
        public virtual Gender Gender5 { get; set; }
        public virtual Gender Gender6 { get; set; }
        public virtual Gender Gender7 { get; set; }
        public virtual Gender Gender8 { get; set; }
        public virtual Gender Gender9 { get; set; }
        public virtual Gender Gender10 { get; set; }
        public virtual Gender Gender11 { get; set; }
        public virtual Gender Gender12 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
        public virtual User User7 { get; set; }
        public virtual User User8 { get; set; }
        public virtual User User9 { get; set; }
        public virtual User User10 { get; set; }
        public virtual User User11 { get; set; }
    }
}
