//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Staffid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public short Positionid { get; set; }
        public string Email_Address { get; set; }
        public string Comments { get; set; }
    }
}
